module.exports = {
  "react/jsx-curly-brace-presence": [
    "error",
    {
      props: "always",
      children: "ignore",
    },
  ],
  "react/destructuring-assignment": ["error", "always", { ignoreClassFields: true }],
  "react/display-name": ["warn"],
  "react/no-access-state-in-setstate": ["error"],
  "react/no-array-index-key": ["error"],
  "react/no-children-prop": ["error"],
  "react/no-danger": ["error"],
  "react/no-deprecated": ["error"],
  "react/no-did-update-set-state": ["error"],
  "react/no-direct-mutation-state": ["error"],
  "react/no-find-dom-node": ["error"],
  "react/no-redundant-should-component-update": ["error"],
  "react/no-typos": ["warn"],
  "react/no-string-refs": ["error"],
  "react/no-this-in-sfc": ["error"],
  "react/no-unescaped-entities": ["error"],
  "react/no-unknown-property": ["error"],
  "react/no-unsafe": ["error"],
  "react/no-will-update-set-state": ["error"],
  "react/prefer-es6-class": ["error", "always"],
  "react/prefer-stateless-function": ["error"],
  "react/require-render-return": ["error"],
  "react/self-closing-comp": ["error", { component: true, html: true }],
  "react/sort-comp": [
    "warn",
    {
      order: ["static-methods", "instance-variables", "lifecycle", "everything-else", "render"],
    },
  ],
  "react/style-prop-object": ["error"],
  "react/prop-types": ["off"],
  "react/void-dom-elements-no-children": ["error"],
  "react/react-in-jsx-scope": ["off"],
};
