module.exports = {
  "react/jsx-curly-brace-presence": [
    2,
    {
      props: `always`,
      children: `ignore`,
    },
  ],
  "react/destructuring-assignment": [2, `always`, { ignoreClassFields: true }],
  "react/display-name": [1],
  "react/no-access-state-in-setstate": [2],
  "react/no-array-index-key": [2],
  "react/no-children-prop": [2],
  "react/no-danger": [2],
  "react/no-deprecated": [2],
  "react/no-did-update-set-state": [2],
  "react/no-direct-mutation-state": [2],
  "react/no-find-dom-node": [2],
  "react/no-redundant-should-component-update": [2],
  "react/no-typos": [1],
  "react/no-string-refs": [2],
  "react/no-this-in-sfc": [2],
  "react/no-unescaped-entities": [2],
  "react/no-unknown-property": [2],
  "react/no-unsafe": [2],
  "react/no-will-update-set-state": [2],
  "react/prefer-es6-class": [2, `always`],
  "react/prefer-stateless-function": [2],
  "react/react-in-jsx-scope": [2],
  "react/require-render-return": [2],
  "react/self-closing-comp": [2, { component: true, html: true }],
  "react/sort-comp": [
    1,
    {
      order: [
        `static-methods`,
        `instance-variables`,
        `lifecycle`,
        `everything-else`,
        `render`,
      ],
    },
  ],
  "react/style-prop-object": [2],
  "react/prop-types": [0],
  "react/void-dom-elements-no-children": [2],
};
